[package]
name = "data_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
femme = "2.2.1"
log = "0.4.22"
protobuf = "3.7.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
